name: Deploy to Neocities

on:
  push:
    branches:
      - Proyecto-0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Subir pagina-web a Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: pagina-web
